// <auto-generated />
using System;
using Dragonarium.Services.Contexts;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dragonarium.Services.Migrations
{
    [DbContext(typeof(DragonariumDbContext))]
    [Migration("20231106191047_HabitatElementsII")]
    partial class HabitatElementsII
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dragonarium.Models.Item", b =>
                {
                    b.Property<Guid>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icon")
                        .HasColumnType("longchar");

                    b.Property<string>("ItemName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItemID");

                    b.ToTable("Items", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Dragonarium.Models.ItemCurrency", b =>
                {
                    b.Property<Guid>("ItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LkCurrencyID")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("ItemID", "LkCurrencyID");

                    b.HasIndex("LkCurrencyID");

                    b.ToTable("ItemCurrencies", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.LkCurrency", b =>
                {
                    b.Property<int>("CurrencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CurrencyID");

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            CurrencyID = 1,
                            CurrencyName = "Gold",
                            Description = "Gold"
                        },
                        new
                        {
                            CurrencyID = 2,
                            CurrencyName = "Silver",
                            Description = "Silver"
                        });
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragon", b =>
                {
                    b.Property<Guid>("LkDragonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DragonID");

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<string>("DragonName")
                        .HasColumnType("longchar");

                    b.Property<int>("GoldRate")
                        .HasColumnType("integer");

                    b.HasKey("LkDragonID")
                        .HasName("PK_Dragon");

                    b.ToTable("Dragons", (string)null);

                    b.HasData(
                        new
                        {
                            LkDragonID = new Guid("20e8a44d-2a72-498e-826c-116cebb809d6"),
                            Description = "Dragon Desc",
                            DragonName = "Dragon",
                            GoldRate = 0
                        },
                        new
                        {
                            LkDragonID = new Guid("0ad1c046-af89-49af-af72-d397bc2cb57c"),
                            Description = "Dragon Desc II",
                            DragonName = "Dragon II",
                            GoldRate = 0
                        });
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragonEgg", b =>
                {
                    b.Property<Guid>("LkDragonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HatchExp")
                        .HasColumnType("integer");

                    b.HasKey("LkDragonID");

                    b.ToTable("DragonEggs", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragonElement", b =>
                {
                    b.Property<Guid>("LkDragonID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DragonID");

                    b.Property<int>("LkElementID")
                        .HasColumnType("integer")
                        .HasColumnName("ElementID");

                    b.HasKey("LkDragonID", "LkElementID")
                        .HasName("PK_DragonElement");

                    b.HasIndex("LkElementID");

                    b.ToTable("DragonElements", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.LkElement", b =>
                {
                    b.Property<int>("LkElementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ElementName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LkElementID");

                    b.ToTable("Elements", (string)null);

                    b.HasData(
                        new
                        {
                            LkElementID = 1,
                            Description = "Water",
                            ElementName = "Water"
                        },
                        new
                        {
                            LkElementID = 2,
                            Description = "Earth",
                            ElementName = "Earth"
                        },
                        new
                        {
                            LkElementID = 3,
                            Description = "Fire",
                            ElementName = "Fire"
                        },
                        new
                        {
                            LkElementID = 4,
                            Description = "Air",
                            ElementName = "Air"
                        });
                });

            modelBuilder.Entity("Dragonarium.Models.LkHabitat", b =>
                {
                    b.Property<Guid>("HabitatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HabitatID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HabitatName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("HabitatID")
                        .HasName("PK_Habitat");

                    b.ToTable("Habitats", (string)null);

                    b.HasData(
                        new
                        {
                            HabitatID = new Guid("f6fa9d16-3fdc-4773-907a-7866a1ad1f34"),
                            Description = "Habitat Desc",
                            HabitatName = "Habitat"
                        });
                });

            modelBuilder.Entity("Dragonarium.Models.LkHabitatElement", b =>
                {
                    b.Property<Guid>("LkHabitatID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LkElementID")
                        .HasColumnType("integer");

                    b.HasKey("LkHabitatID", "LkElementID");

                    b.HasIndex("LkElementID");

                    b.ToTable("HabitatElements", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.DragonEggItem", b =>
                {
                    b.HasBaseType("Dragonarium.Models.Item");

                    b.Property<Guid>("LkDragonID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("LkDragonID");

                    b.ToTable("DragonEggItems", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.HabitatItem", b =>
                {
                    b.HasBaseType("Dragonarium.Models.Item");

                    b.Property<Guid>("LkHabitatID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("LkHabitatID");

                    b.ToTable("HabitatItems", (string)null);
                });

            modelBuilder.Entity("Dragonarium.Models.ItemCurrency", b =>
                {
                    b.HasOne("Dragonarium.Models.Item", "Item")
                        .WithMany("ItemCurrencies")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ItemCurrency_Item");

                    b.HasOne("Dragonarium.Models.LkCurrency", "LkCurrency")
                        .WithMany()
                        .HasForeignKey("LkCurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LkCurrency");
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragonEgg", b =>
                {
                    b.HasOne("Dragonarium.Models.LkDragon", "LkDragon")
                        .WithOne()
                        .HasForeignKey("Dragonarium.Models.LkDragonEgg", "LkDragonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DragonEgg_Dragon");

                    b.Navigation("LkDragon");
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragonElement", b =>
                {
                    b.HasOne("Dragonarium.Models.LkDragon", "LkDragon")
                        .WithMany("DragonElements")
                        .HasForeignKey("LkDragonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DragonElement_Dragon");

                    b.HasOne("Dragonarium.Models.LkElement", "LkElement")
                        .WithMany()
                        .HasForeignKey("LkElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DragonElement_Element");

                    b.Navigation("LkDragon");

                    b.Navigation("LkElement");
                });

            modelBuilder.Entity("Dragonarium.Models.LkHabitatElement", b =>
                {
                    b.HasOne("Dragonarium.Models.LkElement", "LkElement")
                        .WithMany()
                        .HasForeignKey("LkElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonarium.Models.LkHabitat", "LkHabitat")
                        .WithMany("LkHabitatElements")
                        .HasForeignKey("LkHabitatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LkElement");

                    b.Navigation("LkHabitat");
                });

            modelBuilder.Entity("Dragonarium.Models.DragonEggItem", b =>
                {
                    b.HasOne("Dragonarium.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Dragonarium.Models.DragonEggItem", "ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonarium.Models.LkDragon", "LkDragon")
                        .WithMany()
                        .HasForeignKey("LkDragonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LkDragon");
                });

            modelBuilder.Entity("Dragonarium.Models.HabitatItem", b =>
                {
                    b.HasOne("Dragonarium.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("Dragonarium.Models.HabitatItem", "ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonarium.Models.LkHabitat", "LkHabitat")
                        .WithMany()
                        .HasForeignKey("LkHabitatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LkHabitat");
                });

            modelBuilder.Entity("Dragonarium.Models.Item", b =>
                {
                    b.Navigation("ItemCurrencies");
                });

            modelBuilder.Entity("Dragonarium.Models.LkDragon", b =>
                {
                    b.Navigation("DragonElements");
                });

            modelBuilder.Entity("Dragonarium.Models.LkHabitat", b =>
                {
                    b.Navigation("LkHabitatElements");
                });
#pragma warning restore 612, 618
        }
    }
}
